vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        animals:
            uri_prefix: /images/animals
            upload_destination: '%kernel.project_dir%/public/images/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer